asset_policy:
  embedded:
  - gruene-logo-bund-weiss-cmyk.png
  external:
  - 2026-03-leonore-fuer-flyer.png
  - green-pine-trees-covered-with-fog.jpg
  shipped: []
build:
  output: template.sla
  script: build.py
format: A4
id: 26-03-flyer-a6-hochformat-gruenes-cover
idml_source: ../../../../originals/26-03-Flyer A6 Hochformat gruenes Cover Ordner/26-03-Flyer
  A6 Hochformat gruenes Cover.idml
previews_for_sla: 2fdc38b4740558b1e4f66e0aa23195437d0934529f34e2e972952b03e9f2c6ed
title: 26-03-flyer-a6-hochformat-gruenes-cover
version: 0.1.0
build_py_sha256: e8daf418274ab79687c9ec388b00ae9bf11245566987fa947e0d11cd07d34891
