asset_policy:
  embedded:
  - gruene-logo-bund-weiss-cmyk.png
  external:
  - 26-05-25-gewessler-gruenen-odd-0452-2.jpg
  - 26-05-25-gewessler-gruenen-odd-0452-2.png
  - green-pine-trees-covered-with-fog.jpg
  - green-pine-trees-covered-with-fog.png
  - plakat-dunkel-fuer-flyer.png
  - schwarzer-verlauf-radial.png
  shipped: []
build:
  output: template.sla
  script: build.py
format: A4
id: 26-03-flyer-a6-hochformat-portrait
idml_source: ../../../../originals/26-03-Flyer A6 Hochformat Portrait Ordner/26-03-Flyer
  A6 Hochformat Portrait.idml
previews_for_sla: ceee0f3f773c032f93a30b64f295ad82152e1c4cde71696618e178d5c015ae1e
title: 26-03-flyer-a6-hochformat-portrait
version: 0.1.0
build_py_sha256: 4809a5313c92c4657808691d9b0619edafde632cb8043219926df288281c2b89
