asset_policy:
  embedded:
  - gruene-logo-bund-weiss-cmyk.png
  external:
  - green-pine-trees-covered-with-fog.png
  - leonore-sitzend-kopie.png
  - schwarzer-verlauf-radial.png
  shipped: []
build:
  output: template.sla
  script: build.py
format: A4
id: 26-03-flyer-a6-querformat-quadrat-in-bild
idml_source: ../../../../originals/26-03-Flyer A6 Querformat Quadrat in Bild Ordner/26-03-Flyer
  A6 Querformat Quadrat in Bild.idml
previews_for_sla: a6647514aac71d484e8d37674064154e78e656ecb2747dc65c4f1ca35dd6e4cd
title: 26-03-flyer-a6-querformat-quadrat-in-bild
version: 0.1.0
build_py_sha256: 2616ff8e43359d57fbf06b68689a64ba447d64d4a11299496455f53af4195ca9
