asset_policy:
  embedded:
  - bluesky-weiss.png
  - gruene-logo-bund-weiss-cmyk.png
  - mail-weiss.png
  - social-media-icons-weiss.png
  - website-weiss.png
  external:
  - green-pine-trees-covered-with-fog.jpg
  - plakat-dunkel-fuer-flyer.png
  shipped: []
build:
  output: template.sla
  script: build.py
format: A4
id: 26-03-leporello-z-falz-99x210-6-seitig-gruenes-cover
idml_source: ../../../../originals/26-03-Leporello z-Falz 99x210 6-seitig gruenes
  Cover Ordner/26-03-Leporello z-Falz 99x210 6-seitig gruenes Cover.idml
previews_for_sla: 368170e05103a13d807c8b553730c203648b91f427488ea3c5d883b9fd748688
title: 26-03-leporello-z-falz-99x210-6-seitig-gruenes-cover
version: 0.1.0
build_py_sha256: 87d61c01be2ae298c25553d23732620ebde17f9ea538f69ec260923c1b80bd73
