asset_policy:
  embedded:
  - gruene-logo-bund-weiss-cmyk.png
  external:
  - green-pine-trees-covered-with-fog.jpg
  - plakat-dunkel-fuer-flyer.png
  - ziesel.jpg
  shipped: []
build:
  output: template.sla
  script: build.py
format: A4
id: 26-03-flyer-a6-querformat-zweigeteilt
idml_source: ../../../../originals/26-03-Flyer A6 Querformat zweigeteilt Ordner/26-03-Flyer
  A6 Querformat zweigeteilt.idml
previews_for_sla: 36d3b2400eb14aead71896845634a828231fb3c0ee0fe3d08e5d0091f2233135
title: 26-03-flyer-a6-querformat-zweigeteilt
version: 0.1.0
build_py_sha256: 75f9caf6309b6fe29ad235c12251c96c6ca173fc3fade1f55178cce9bb038aa1
