asset_policy:
  embedded:
  - gruene-logo-bund-weiss-cmyk.png
  external:
  - 2026-03-leonore-fuer-flyer.png
  - green-pine-trees-covered-with-fog.png
  - plakat-dunkel-fuer-flyer.png
  shipped: []
build:
  output: template.sla
  script: build.py
format: A4
id: 26-03-flyer-a6-querformat-portrait
idml_source: ../../../../originals/26-03-Flyer A6 Querformat Portrait Ordner/26-03-Flyer
  A6 Querformat Portrait.idml
previews_for_sla: e3f077093d9aa96a33f41064056173ef9aa6971504e3a8c810935f182137fba5
title: 26-03-flyer-a6-querformat-portrait
version: 0.1.0
build_py_sha256: 4371a9450049264eed988c7da8b15159fa2781f9cd611b41ec3ea7b3912a9bac
