asset_policy:
  embedded:
  - gruene-logo-bund-weiss-cmyk.png
  external:
  - 2026-03-leonore-fuer-flyer.png
  - green-pine-trees-covered-with-fog.png
  - plakat-dunkel-fuer-flyer.png
  shipped: []
build:
  output: template.sla
  script: build.py
format: A4
id: 26-03-flyer-a6-querformat-portrait
idml_source: ../../../../originals/26-03-Flyer A6 Querformat Portrait Ordner/26-03-Flyer
  A6 Querformat Portrait.idml
previews_for_sla: 2b6a58808cbed873a45cafc1408b1b74b63b2e213a4af53e0073f6d795540a0b
title: 26-03-flyer-a6-querformat-portrait
version: 0.1.0
build_py_sha256: 39c390c9df39b2f02d346858f6f5c2c78be2012e1d64249701cb30a80274bdd0
